swagger: "2.0"
info:
  description: "API for obtaining entities."
  version: "1.0.0"
  title: "Entities API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/"
schemes:
- "http"
paths:
  /api/entities/:
    get:
      tags:
      - "Entities"
      summary: "Get a list of entities"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      responses:
        400:
          description: "Server error"
  /api/entities/{entityId}:
    get:
      tags:
      - "Entities"
      summary: "Get a single entity by id"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name : "entityId"
        in: "path"
        description: "ID of entity that needs to be updated"
        required: true
        type: "string"
        format: "string"
      responses:
        400:
          description: "Server error"
    post:
      tags:
      - "Entities"
      summary: "Adds an entity"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name : "entityId"
        in: "path"
        description: "ID of entity that needs to be updated"
        required: true
        type: "string"
        format: "string"
      responses:
        400:
          description: "Server error"

 
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"